dist: xenial
language: scala
jdk: openjdk8
matrix:
  include:
  - env: SBT_VERSION="0.13.18"
  - env: SBT_VERSION="1.2.8"
script:
  - sbt "^^ ${SBT_VERSION}" test scripted
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
