language: scala
matrix:
  include:
  - env: SBT_VERSION="0.13.16"
  - env: SBT_VERSION="1.0.1"
script:
  - jdk_switcher use openjdk8
  - sbt "^^ ${SBT_VERSION}" test scripted
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
sudo: false
